on: [push]
name: Azure ARM

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: policy-demo-github-actions
        template: ./azuredeploy.json
        parameters: azuredeploy.parameters.json
    - run: echo ${{ steps.deploy.outputs.containerName }}